lane :test do
  android_get_version_name(
    gradle_file: "app/build.gradle" # optional
  )

  android_set_version_name(
    version_name: "1.23.4",
    gradle_file: "app/build.gradle" # optional
  )

  android_get_version_code(
    gradle_file: "app/build.gradle" # optional
  )

  android_set_version_code(
    version_code: 17, # optional, if not specified, Version Code will be incremented
    gradle_file: "app/build.gradle" # optional
  )
end

lane :flutter_test do 
  android_get_version_name(
    gradle_file: "app/flutter-build.gradle"
  )

  android_set_version_name(
    version_name: "1.23.4",
    gradle_file: "app/flutter-build.gradle"
  )

  android_get_version_code(
    gradle_file: "app/flutter-build.gradle"
  )

  android_set_version_code(
    version_code: 17, # optional, if not specified, Version Code will be incremented
    gradle_file: "app/flutter-build.gradle" 
  )
end
